development:
  access_key_id: AKIAIIE6B7BA475DGKEA
  secret_access_key: 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
production:
  access_key_id: AKIAIIE6B7BA475DGKEA
  secret_access_key: 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
